version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "wojtek-sharding-learning"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1r5nl92kwlutb"
s3_prefix = "wojtek-sharding-learning"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
